### ISSUE TITLE
fix: Resolve 14 failing circle behavioral tests after PR merge

### ISSUE THREAD

**Issue by cypriannwokolo2-creator** [cocor-tech/moistello-contracts#398]
## Description
After merging PRs #263, #264, #265, and #266, there are 14 behavioral test failures in the circle package. These are test assertions that don't match the new contract behavior, not compilation errors.

## Failing Tests
- `test_raise_dispute_not_member` - PR #266 added member validation to raise_dispute
- `test_resolve_dispute_not_admin` - Resolution logic changed
- `test_claim_referral_bonus` - Referral bonus logic updated
- `test_batch_payout_fixed_order` - Fixed order payout behavior changed
- Various payout type tests

## Requirements
- Update test assertions to match new contract behavior
- Ensure all behavioral tests pass after updates
- Verify no regression in existing passing tests

## Acceptance Criteria
- [ ] All 14 failing tests updated and passing
- [ ] No regression in existing passing tests
- [ ] Test coverage maintained at 95%+

## Priority
High

**Comment by Ameer-5-5** [comment]
@Ameer-5-5 has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> Hello sir maintainer....
> I have a vast experience in solving github issues ...
> Please do well to assign me this let me get it done for you ✅.
> Thank you 😊 


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/4f0c6d14-806f-42cd-b4ad-77d9ce1385da) or assign @Ameer-5-5 to this issue.

**Comment by nasirudeenbadirudeen87-cloud** [comment]
@nasirudeenbadirudeen87-cloud has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> Maintainer, I’m happy to take this one. After reviewing the codebase, I’m comfortable with the approach and ready to get started. I’ll keep the scope focused, add solid test coverage, and ensure CI stays green. I’d be glad to open a draft early so we can confirm the direction together


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/4f0c6d14-806f-42cd-b4ad-77d9ce1385da) or assign @nasirudeenbadirudeen87-cloud to this issue.

**Comment by kike-alt** [comment]
@kike-alt has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> Hello, I'd like to pick this issue up.
> 
> I'll dig into the reported behavior, identify the underlying cause, and fix it with test coverage to prevent a regression.
> 
> Planned approach, based on the acceptance criteria:
> - All 14 failing tests updated and passing
> - No regression in existing passing tests
> - Test coverage maintained at 95%+
> 
> Happy to get started right away if assigned — looking forward to contributing.


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/4f0c6d14-806f-42cd-b4ad-77d9ce1385da) or assign @kike-alt to this issue.

**Comment by Ceepr1an** [comment]
@Ceepr1an has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> I can work on this issue 


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/4f0c6d14-806f-42cd-b4ad-77d9ce1385da) or assign @Ceepr1an to this issue.

**Comment by collinsezedike** [comment]
@collinsezedike has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> GM Cyprian, let me help you with this issue.
> 
> The dangerous failure mode here isn't leaving a test broken, it's fixing a test by making its assertion match whatever the new code happens to do, without checking that the new behavior is actually correct per what PRs #263-266 intended. "Update assertions to match new contract behavior" is not the same instruction as "make the assertions pass," the former requires reading each merged PR to understand the intended change, the latter risks silently codifying a regression as the new expected behavior.
> 
> Here's my plan:
> 
> - Read #263, #264, #265, #266 individually to understand what each was actually supposed to change, not just run the tests and adjust assertions to whatever currently happens
> - For `test_raise_dispute_not_member`: confirm #266's member validation rejects the correct error case, then update the test to assert the new expected error/behavior, not just whatever error currently surfaces
> - For `test_resolve_dispute_not_admin`: trace the resolution logic change to confirm the new authorization behavior is what was intended, then update the assertion accordingly
> - For `test_claim_referral_bonus` and the payout-type tests: verify the updated bonus/payout math against the PR's stated intent, not just the code's current output, since a test that merely mirrors current output can't catch a bug introduced by that same PR
> - For `test_batch_payout_fixed_order`: confirm the new fixed-order behavior is deterministic and matches what was designed, not just consistent across repeated runs
> - Run the full suite after updates to confirm no other previously-passing test regressed as a side effect of these changes
> - Confirm coverage stays at 95%+ after the update
> 
> If any of the four PRs' actual intent is ambiguous from the diff alone, I'd flag that to you directly rather than guess and encode a possibly-wrong behavior into the test suite as if it were correct. Happy to start as soon as I'm assigned.


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/4f0c6d14-806f-42cd-b4ad-77d9ce1385da) or assign @collinsezedike to this issue.

**Comment by dimin4241-svg** [comment]
@dimin4241-svg has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> I have hands-on experience maintaining Rust contract test suites after behavior changes. I reviewed the listed circle failures and can update only assertions that no longer match the merged semantics, add regression checks where needed, and run the full workspace tests. I can complete this within 1–2 days of assignment. Please assign it to me.


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/4f0c6d14-806f-42cd-b4ad-77d9ce1385da) or assign @dimin4241-svg to this issue.
